"""Regenerates src/render/craft-art.js from docs/craft-sheet.png.

The sheet is a design mock-up: four aircraft, nose up, each on its own dark
card. For each one the card background is flood-filled inwards from the crop
borders -- interior darks (canopies, nozzles, panel lines) are not reachable
from the edge, so they survive -- then the result is trimmed, rotated so the
nose points along +X to match the vector sprites' convention, scaled to a
common wingspan and inlined as a data URI.

    pip install pillow && python3 tools/extract_craft_art.py

The selected card in the mock-up is a flatter, much darker panel than the
others, so it gets its own luminance cutoff.
"""
import base64
import os
from collections import deque

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET = os.path.join(ROOT, 'docs', 'craft-sheet.png')
OUT = os.path.join(ROOT, 'src', 'render', 'craft-art.js')
WINGSPAN = 116

# name, crop box in the sheet, background luminance cutoff
JOBS = [
    ('viper', (186, 192, 410, 418), 45),
    ('dragon', (501, 178, 801, 420), 118),
    ('eagle', (868, 178, 1168, 420), 118),
    ('swind', (1229, 178, 1529, 420), 118),
]


def cut_out(image, cutoff):
    image = image.convert('RGBA')
    width, height = image.size
    pixels = image.load()

    def is_background(pixel):
        r, g, b = pixel[:3]
        # Dark and blue-leaning: the aircraft are bright, and their warm parts
        # (exhaust, roundels) are red-dominant.
        return 0.299 * r + 0.587 * g + 0.114 * b < cutoff and b >= r - 6

    queue = deque()
    for x in range(width):
        queue.append((x, 0))
        queue.append((x, height - 1))
    for y in range(height):
        queue.append((0, y))
        queue.append((width - 1, y))

    seen = bytearray(width * height)
    while queue:
        x, y = queue.popleft()
        if x < 0 or y < 0 or x >= width or y >= height or seen[y * width + x]:
            continue
        if not is_background(pixels[x, y]):
            continue
        seen[y * width + x] = 1
        pixels[x, y] = (0, 0, 0, 0)
        queue.extend(((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)))
    return image


def main():
    sheet = Image.open(SHEET).convert('RGB')
    entries = []
    for name, box, cutoff in JOBS:
        art = cut_out(sheet.crop(box), cutoff)
        art = art.crop(art.getbbox()).rotate(-90, expand=True)
        scale = WINGSPAN / art.height
        art = art.resize((max(1, round(art.width * scale)), WINGSPAN), Image.LANCZOS)
        png = os.path.join(ROOT, 'docs', f'craft-{name}.png')
        art.save(png, optimize=True)
        with open(png, 'rb') as handle:
            encoded = base64.b64encode(handle.read()).decode()
        os.remove(png)
        entries.append(f"  {name}: 'data:image/png;base64,{encoded}',")
        print(f'{name}: {art.size[0]}x{art.size[1]}, {len(encoded)} base64 chars')

    body = '\n'.join(entries)
    with open(OUT, 'w') as handle:
        handle.write(
            '/**\n'
            ' * Craft artwork, embedded so the game stays a single self-contained page.\n'
            ' *\n'
            ' * Generated by tools/extract_craft_art.py from docs/craft-sheet.png.\n'
            ' * Do not hand-edit; re-run the tool instead.\n'
            ' */\n'
            'export const CRAFT_ART = {\n'
            f'{body}\n'
            '};\n'
        )
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
